### ISSUE TITLE
Update ResourceContainerFactory packaging parameters 

### ISSUE THREAD

**Issue by aucoindan** [space-logistics-org/spacenet-java#5]
Use CTBE parameters outlined in:

Goodliff, K. E., Stromgren, C., Dickert, Z., Ewert, M. K., Hill, J., &amp; Moore, C. (2017). Logistics needs for future human exploration beyond low Earth orbit. AIAA SPACE and Astronautics Forum and Exposition. https://doi.org/10.2514/6.2017-5122

**Comment by aucoindan** [comment]
![CTBParameters](https://user-images.githubusercontent.com/61364880/167431924-1b2bb60e-ed5e-4a8d-ae6d-8af170e74f1b.jpg)

page 13

**Comment by ptgrogan** [comment]
Thanks @aucoindan -- for posterity, the prior CTB parameters were based on a maximal shuttle "locker" configuration (e.g., see slides 22-25 on "[Introduction to Habitability," Course Notes for ENAE 697 Space Human Factors and Life Support, David L. Akin, 2013](https://spacecraft.ssl.umd.edu/academics/697S13/697S13L10.habitability2x.pdf)). 

The new data from Goodliff et al. above has lower tare mass from improved materials, mass capacity in line with the prior "strapped" configuration (probably driven by human factors more than anything), and volume/external volume driven by existing geometry.
